# Generated by Django 2.2.13 on 2021-03-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('mark', models.CharField(max_length=256, verbose_name='标签')),
                ('title', models.CharField(max_length=64, verbose_name='帖子标题')),
                ('content', models.CharField(max_length=1024, verbose_name='帖子正文')),
                ('img', models.CharField(max_length=128, null=True, verbose_name='帖子图片')),
                ('intro', models.CharField(max_length=256, verbose_name='帖子简介')),
                ('view_n', models.IntegerField(verbose_name='阅读数')),
                ('is_delete', models.BooleanField(verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=64, verbose_name='公告标题')),
                ('a_content', models.CharField(max_length=3000, null=True, verbose_name='公告内容')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.IntegerField(verbose_name='回复类型')),
                ('pid', models.IntegerField(verbose_name='parent id')),
                ('img', models.CharField(max_length=128, null=True, verbose_name='回复图片')),
                ('content', models.CharField(max_length=256, verbose_name='回复内容')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='留言时间')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('nick_name', models.CharField(max_length=64, verbose_name='昵称')),
                ('mail', models.CharField(max_length=64, verbose_name='邮箱')),
                ('desc', models.CharField(max_length=256, verbose_name='简介')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('score', models.IntegerField(verbose_name='积分')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
