# Generated by Django 2.2.13 on 2021-03-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='用户id'),
        ),
    ]
